test

diff --git a/.github/workflows/publish-plugin.yml b/.github/workflows/publish-plugin.yml
--- a/.github/workflows/publish-plugin.yml
+++ b/.github/workflows/publish-plugin.yml
@@ -1,5 +1,3 @@
-# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins
-
 name: Release New Official Plugin Version
 on:
   workflow_call:
@@ -7,6 +5,7 @@ on:
   check_run:
     types:
       - completed
+
 jobs:
   validate:
     runs-on: ubuntu-latest
@@ -19,7 +18,7 @@ jobs:
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           output_result: true
-      
+
       - name: Release Drafter
         uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 #v6
         if: steps.verify-ci-status.outputs.result == 'success'
@@ -49,19 +48,12 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      
-      - name: Set up JDK 8
+
+      - name: Set up JDK 11
         uses: actions/setup-java@v4.2.1
         with:
           distribution: temurin
           java-version: 11
-      
-      # - name: Release
-      #   uses: jenkins-infra/jenkins-maven-cd-action@5f5529707ac2bef1ff86da2553ce465ed669aa65  #v1.3.3
-      #   with:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
-      #     MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
 
       - name: Create a new Git tag
         id: create-tag
@@ -71,8 +63,7 @@ jobs:
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git tag -a "$TAG_NAME" -m "Automatically created tag: $TAG_NAME"
           git push origin "$TAG_NAME"
-          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
-          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
+          echo "TAG_NAME=$TAG_NAME" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
 
       - name: Create a new GitHub Release
         id: create-release
@@ -81,7 +72,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ env.TAG_NAME }}
-          release_name: "Release ${{ env.TAG_NAME }}"
+          release_name: "${{ env.TAG_NAME }}"
           body: "This release was automatically created."
           draft: false
           prerelease: false
@@ -90,15 +81,18 @@ jobs:
         id: get_new_tag
         run: |
           TAG_NAME=$(git describe --tags --abbrev=0)
-          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
-          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
+          echo "Extracted Tag Name: $TAG_NAME"
+          echo "TAG_NAME=$TAG_NAME" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
 
       - name: Get GitHub Release Upload URL
         id: get-release
         run: |
-          UPLOAD_URL=$(gh api /repos/${{ github.repository }}/releases --jq '.[] | select(.tag_name=="${{ env.TAG_NAME }}") | .upload_url')
-          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV
-          echo "upload_url=${UPLOAD_URL}" >> $GITHUB_OUTPUT
+          UPLOAD_URL=$(gh api /repos/${{ github.repository }}/releases --jq ".[] | select(.tag_name==\"${{ env.TAG_NAME }}\") | .upload_url")
+          if [[ -z "$UPLOAD_URL" ]]; then
+            echo "❌ ERROR: Failed to retrieve upload URL"
+            exit 1
+          fi
+          echo "UPLOAD_URL=$UPLOAD_URL" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -106,8 +100,12 @@ jobs:
         id: extract_cli_version
         run: |
           CLI_VERSION=$(mvn -B -ntp help:evaluate -Dexpression=cli.version -q -DforceStdout)
-          echo "CLI_VERSION=${CLI_VERSION}" >> $GITHUB_ENV
-          echo "cli_version=${CLI_VERSION}" >> $GITHUB_OUTPUT
+          if [[ -z "$CLI_VERSION" ]]; then
+            echo "❌ ERROR: Failed to extract CLI version"
+            exit 1
+          fi
+          echo "Extracted CLI Version: $CLI_VERSION"
+          echo "CLI_VERSION=$CLI_VERSION" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
 
       - name: Upload Release Asset
         id: upload-release-asset
@@ -121,7 +119,7 @@ jobs:
           asset_name: checkmarx-ast-scanner.hpi
           asset_content_type: application/multipart-core
           overwrite: true
-  
+
   notify:
     needs: release
     uses: Checkmarx/plugins-release-workflow/.github/workflows/release-notify.yml@main
